name: Master commit.

on:
  push:
    branches: [ master ]

jobs:
  Test:
    name: build, test and release on new version.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0
        
      - name: Unit tests
        run: dotnet test Calculator/Calculator.sln
        
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Calculator/Calculator/Calculator.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
   
